services:
  stable-diffusion:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["all"]
              capabilities: [gpu]
    ports:
      - 17861:17861
    volumes:
      - .:/products/app/
      - /home/samuel/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/:/root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/
    restart: unless-stopped
      # entrypoint: ["python","-m","http.server"]
